import type { Metadata } from "next";
import { Overlock_SC } from "next/font/google";
import "./globals.css";

const overlockSC = Overlock_SC({
  subsets: ["latin"],
  weight: ["400"], 
  variable: "--font-overlock-sc", 
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${overlockSC.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
